name: Sphinx Documentation
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies for nbsphinx
      run: |
        sudo apt update
        sudo apt install -y pandoc
    - name: Run Pandoc
      run: |
        pandoc --version        
    - name: Install Poetry.
      uses: snok/install-poetry@v1.3

    - name: install
      run: poetry install

    - name: Build documentation.
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        make sphinx-html
        cp -r _build/html/* ../gh-pages/

    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        force: true
        folder: gh-pages
