# Built from:
# https://github.com/actions/checkout/
# https://github.com/actions/setup-python/
# https://github.com/codecov/codecov-action

name: Build and test linkml-store

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
        mongodb-version: ['7.0']

    runs-on: ${{ matrix.os }}

    steps:

      #----------------------------------------------
      #          install poetry
      #----------------------------------------------
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install library
        run: |
          poetry install --no-interaction --all-extras

      - name: Check common spelling errors
        run: poetry run tox -e codespell


      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test with pytest
        run: poetry run pytest -m "not integration and not neo4j" --ignore=src/linkml_store/inference/implementations/rag_inference_engine.py tests
