name: linkml-store QC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.11" ]
        mongodb-version: ['7.0']

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        
      - name: Install dependencies
        run: poetry install --no-interaction --all-extras

      - name: Check common spelling errors
        run: poetry run tox -e codespell

      #- name: Check code quality with flake8
      #  run: poetry run tox -e lint

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Wait for MongoDB to be Ready
        run: |
          for i in {1..10}; do
            if mongosh --eval "db.runCommand({ ping: 1 })"; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB to start..."
            sleep 5
          done
          echo "MongoDB failed to start"
          exit 1

      - name: Test with pytest and generate coverage file
        run: poetry run pytest -m "not integration and not neo4j" --ignore=src/linkml_store/inference/implementations/rag_inference_engine.py tests
